### ISSUE TITLE
Make `Kungfuig.Supervisor` name configurable 

### ISSUE THREAD

**Issue by am-kantox** [kantox/kungfuig#7]
```diff
defmodule Kungfuig.Supervisor do
  [...]
  def start_link(opts \\ []) do
-    Supervisor.start_link(__MODULE__, opts, name: __MODULE__)
+    {name, opts} = Keyword.pop(opts, :name, __MODULE__)
+    Supervisor.start_link(__MODULE__, opts, name: name)
  end
```

**Comment by vbroskas** [comment]
Hi @am-kantox ! For the name are you wanting to pass in an atom, or should the name be registered with a `:via` tuple or something else? I made the changes you have above for passing in an atom as the name, now I'm working on the tests.

Currently I'm passing in the supervisor name to `Kungfuig.config(name, which)` so the call to `Supervisor.which_children()` works, but I'm not sure if that's a good way to go about this. Let me know if this approach is bad and I'll scrap it. Thanks for the help!

**Comment by am-kantox** [comment]
> For the name are you wanting to pass in an atom, or should the name be registered with a `:via` tuple or something else?

Hi @vbroskas! Thanks for stepping in, appreciate that. I believe anything that works for [name registration](https://hexdocs.pm/elixir/GenServer.html#module-name-registration) should work for us. Basically, it’s [`GenServer.name()`](https://hexdocs.pm/elixir/GenServer.html#t:name/0) type.

> I'm working on the tests.

Cool. I believe starting two supervisors with different names and ensuring they are both functioning as expected is enough, but it’s all up to you.

> Currently I'm passing in the supervisor name to `Kungfuig.config(name, which)` so the call to `Supervisor.which_children()` works, but I'm not sure if that's a good way to go about this. Let me know if this approach is bad and I'll scrap it.

I like the second parameter in the call to `config/2`, but I prefer the name parameter to be optional, with the default value of `Kungfuig.Supervisor` to make it still transparent for those who do not need several servers. Somewhat like

```elixir
@spec config(
    supervisor :: Supervisor.supervisor(), which :: atom() | [atom()] | nil
  ) :: Kungfuig.t()
def config(supervisor \\ Kungfuig.Supervisor, which) do
  ...
  supervisor
  |> Supervisor.which_children()
  ...
```

> Thanks for the help!

Thank you!

**Comment by am-kantox** [comment]
Closed by #8.

**Comment by am-kantox** [comment]
Hi @vbroskas !

After doing some internal tests with existing code using `Kungfuig`, I accidentally noted that we broke the backward compatibility for calls like `Kungfuig.config(:which)`, so I swapped the arguments in a call to `Kungfuig.config/2` as

```elixir
def config(which \\ nil, supervisor \\ Kungfuig.Supervisor) do
```

Also, I have added `CaptureLog` and the test output is now clean.

**Comment by vbroskas** [comment]
Ok cool, thanks for the heads up! I'll make sure to keep the same order of function arguments in the future  :)
